import { NextResponse } from "next/server";
import {
  getMarketServiceById,
  getMarketServiceCallById,
} from "@/lib/market-services";

export const dynamic = "force-dynamic";
export const maxDuration = 120;

type OpenAIImageResponse = {
  data?: Array<{
    b64_json?: string;
    url?: string;
    revised_prompt?: string;
  }>;
  usage?: unknown;
  error?: {
    message?: string;
  };
};

function asObject(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function firstString(values: unknown[]) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim();
  }
  return "";
}

function enumString(value: unknown, allowed: string[], fallback: string) {
  if (typeof value !== "string") return fallback;
  const normalized = value.trim().toLowerCase();
  return allowed.includes(normalized) ? normalized : fallback;
}

async function assertMarketCall(request: Request, capability: string) {
  const serviceId = Number(request.headers.get("x-ottoauth-service-id") ?? 0);
  const callId = request.headers.get("x-ottoauth-call-id")?.trim() ?? "";
  if (!Number.isInteger(serviceId) || serviceId <= 0 || !callId) {
    return {
      error: NextResponse.json(
        { error: "Missing OttoAuth Pay service/call headers." },
        { status: 402 },
      ),
    };
  }

  const [call, service] = await Promise.all([
    getMarketServiceCallById(callId),
    getMarketServiceById(serviceId),
  ]);
  if (!call || !service || call.service_id !== service.id) {
    return {
      error: NextResponse.json({ error: "Market service call not found." }, { status: 404 }),
    };
  }
  if (call.status !== "pending") {
    return {
      error: NextResponse.json({ error: "Market service call is not pending." }, { status: 409 }),
    };
  }
  if (service.capability !== capability) {
    return {
      error: NextResponse.json({ error: "Service capability mismatch." }, { status: 409 }),
    };
  }
  return { call, service };
}

export async function POST(request: Request) {
  const market = await assertMarketCall(request, "generate_image_openai");
  if (market.error) return market.error;

  const body = (await request.json().catch(() => null)) as Record<string, unknown> | null;
  const input = asObject(body?.input);
  const prompt = firstString([input.prompt, input.request, body?.reason]);
  if (!prompt) {
    return NextResponse.json({ error: "input.prompt is required." }, { status: 400 });
  }

  const apiKey = process.env.OPENAI_API_KEY?.trim();
  if (!apiKey) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is not configured for OttoAuth image generation." },
      { status: 503 },
    );
  }

  const model = process.env.OPENAI_IMAGE_MODEL?.trim() || "gpt-image-1";
  const size = enumString(input.size, ["1024x1024", "1024x1536", "1536x1024"], "1024x1024");
  const quality = enumString(input.quality, ["low", "medium", "high", "auto"], "medium");
  const outputFormat = enumString(input.output_format, ["png", "jpeg", "webp"], "png");
  const background = enumString(input.background, ["auto", "opaque", "transparent"], "auto");

  const providerResponse = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      prompt,
      size,
      quality,
      output_format: outputFormat,
      background,
      n: 1,
    }),
  });
  const payload = (await providerResponse.json().catch(() => null)) as OpenAIImageResponse | null;
  if (!providerResponse.ok || !payload) {
    return NextResponse.json(
      {
        error:
          payload?.error?.message ||
          `OpenAI image generation failed with HTTP ${providerResponse.status}.`,
      },
      { status: 502 },
    );
  }

  const first = payload.data?.[0] ?? {};
  const imageDataUrl = first.b64_json
    ? `data:image/${outputFormat};base64,${first.b64_json}`
    : null;

  return NextResponse.json({
    ok: true,
    status: "completed",
    provider: "openai",
    model,
    prompt,
    revised_prompt: first.revised_prompt ?? null,
    image_data_url: imageDataUrl,
    image_url: first.url ?? null,
    usage: payload.usage ?? null,
    summary: "Image generated by OttoAuth via OpenAI.",
  });
}
