import { getBaseUrl } from "@/lib/base-url";
import {
  getAgentClarificationTimeoutLabel,
  getAgentClarificationTimeoutSeconds,
} from "@/lib/computeruse-agent-clarification-config";
import { getAllManifests } from "@/services/registry";

function buildSkill(baseUrl: string): string {
  const clarificationTimeoutLabel = getAgentClarificationTimeoutLabel();
  const clarificationTimeoutSeconds = getAgentClarificationTimeoutSeconds();
  const services = getAllManifests();

  const serviceRows = services
    .map((m) => {
      const toolsCell =
        m.endpoints.length > 0
          ? `\`GET ${baseUrl}/api/services/${m.id}\``
          : "N/A";
      const docsCell = m.docsMarkdown
        ? `\`GET ${baseUrl}/api/services/${m.id}/docs\``
        : "N/A";
      return `| ${m.id} | ${m.status} | ${m.description} | ${toolsCell} | ${docsCell} |`;
    })
    .join("\n");

  return `# ottoauth

OttoAuth is now a **service-first broker** between:

1. **an agent identity** that authenticates with \`username\` + \`privateKey\`
2. **a human OttoAuth account** that can link that agent and own credits
3. **OttoAuth internal fulfillment workers** that actually perform browser work

The public hosted contract you should rely on is:

- agent credentials generated by the human in \`${baseUrl}/dashboard\`
- service discovery under \`${baseUrl}/api/services\`
- service execution under \`${baseUrl}/api/services/<id>\`
- task follow-up endpoints returned by those services

Do **not** assume every other route in the repo is part of the stable hosted agent surface. Some lower-level \`/api/computeruse/*\` routes are device-oriented or dev/migration paths. For normal hosted agent integrations, prefer the service-discovery flow below.

This skill is intentionally about **how to use OttoAuth as an agent caller**. It does not document OttoAuth's worker-side fulfillment protocol.

## If you are an AI agent, start here

Read order:

1. \`${baseUrl}/llms.txt\` — short agent contract and durable links
2. \`${baseUrl}/skill.md\` — this full hosted-agent operating guide
3. \`${baseUrl}/api/services\` — machine-readable service index
4. \`${baseUrl}/api/services/order\` — default general-order tool JSON
5. \`${baseUrl}/api/services/order/docs\` — default general-order markdown docs

Your default integration plan:

1. Ask the human to sign in at \`${baseUrl}/login\`.
2. Ask the human to generate **Agent API Keys** in \`${baseUrl}/dashboard\`.
3. Store the dashboard-generated \`username\` and \`privateKey\` securely.
4. Confirm the human has credits, or that your agent can handle OttoAuth's x402 \`402 Payment Required\` response.
5. Use \`GET ${baseUrl}/api/services\` before calling tools; call only \`active\` or \`beta\` services.
6. For general purchases, pickup orders, delivery orders, cancellations, returns, refunds, and order follow-up, use \`order\`.
7. Submit a structured work order with \`POST ${baseUrl}/api/services/order/submit\`.
8. Save \`task.id\`, \`run_id\`, and \`${baseUrl}/orders/<taskId>\`.
9. Poll \`POST ${baseUrl}/api/services/order/tasks/<taskId>\` every 15-60 seconds.
10. If the task is \`awaiting_agent_clarification\`, answer through your callback URL or the clarification endpoint before the deadline.
11. If the human changes their mind before completion, call \`POST ${baseUrl}/api/services/order/tasks/<taskId>/cancel\`.
12. On completion, report \`summary\`, \`pickup_details\`, \`tracking_details\`, totals, and any relevant run events.

Hard rules:

- Do not ask the human for retailer passwords, card numbers, or one-time payment codes unless the human explicitly chooses to complete that step themselves.
- Do not ask the human to configure callback URLs; if you need clarification webhooks, create an agent-owned account with \`callback_url\` and have the human link its pairing key.
- Do not call lower-level \`/api/computeruse/*\` routes unless you are implementing worker/device fulfillment infrastructure.
- Do not call services marked \`coming_soon\`.
- Do not continue checkout when the reported total exceeds the requested spend cap.

## Current hosted architecture

### 1. Agent credentials

Your human creates OttoAuth agent credentials from \`${baseUrl}/dashboard\`.
They send you:

- \`username\`
- \`privateKey\`

\`privateKey\` is your real credential. Keep it secret. These dashboard-generated credentials are already linked to the human account that created them.

The human dashboard does not collect callback URLs. If your agent needs clarification webhooks for cases where an internal worker gets blocked, set \`callback_url\` when you create or manage an agent-owned OttoAuth account; otherwise poll task status and answer clarification through the clarification endpoint.

### 2. Human setup

Your human must:

1. sign in at \`${baseUrl}/login\`
2. open the **Agent API Keys** section in \`${baseUrl}/dashboard\`
3. send you the dashboard-generated \`username\` and \`privateKey\`
4. make sure their OttoAuth account has credits available, or let your agent satisfy OttoAuth's x402 \`402 Payment Required\` response when more funding is needed

If the agent has no linked human account, or if the linked human account does not have enough credits for the requested spend cap, the main hosted browser-task API returns \`402 Payment Required\` with x402 payment instructions when x402 is configured. Pay OttoAuth and retry with the payment proof to queue the task.

### 3. Scoped commerce mandates

For autonomous buying, include a scoped mandate when you submit an order. OttoAuth evaluates the mandate before x402 funding and before internal fulfillment queueing.

Supported mandate fields:

- \`max_total_cents\`
- \`max_daily_cents\`
- \`allowed_categories\` and \`blocked_categories\`
- \`allowed_merchants\` and \`blocked_merchants\`
- \`approval_required_over_cents\`
- \`expires_at\`

\`max_total_cents\` becomes the spend cap when \`max_charge_cents\` is omitted. Requests outside the mandate return \`403\` with \`commerce_mandate\` details. The current approval threshold behavior is conservative: requests above \`approval_required_over_cents\` are rejected with \`commerce_mandate.status = "approval_required"\` until a dedicated approval handoff exists.

### 4. Internal fulfillment queue

Fulfillment is internal OttoAuth infrastructure, not a user-facing device marketplace.

- For **agent-submitted browser tasks**, OttoAuth routes work to an available internal worker.
- For **human self-serve tasks**, OttoAuth also uses the internal queue.
- Users do not claim fulfillment devices, opt into fulfilling other users' orders, or receive fulfillment payouts.

### 5. Service layer

Once credentials and funding are ready, you interact through services:

1. \`GET ${baseUrl}/api/services\`
2. \`GET ${baseUrl}/api/services/<id>\`
3. call endpoints from that service's machine-readable \`tools[]\`
4. optionally read \`GET ${baseUrl}/api/services/<id>/docs\`

Services with \`status = "coming_soon"\` are discoverable but not callable.

## Hosted availability (current)

- **order** (\`active\`): the single hosted service for human-linked commerce tasks

Available now through \`order\`:

- Amazon orders: set \`store: "amazon"\` and pass a product URL or clear search/order details.
- Snackpass orders: set \`store: "snackpass"\`, include \`merchant\`, and pass item/modifier details.
- Any other supported browser-order work: set \`store\`, \`merchant\`, \`store_url\`, \`order_type\`, \`item_name\`, and \`order_details\` as needed.

Do not call store-specific hosted service endpoints for Amazon or Snackpass. They are intentionally not part of the public agent service registry.

## E-commerce feature coverage

OttoAuth's hosted service surface covers the core e-commerce automation features agents usually need:

- **Auth and API keys:** humans generate dashboard API keys for you; every hosted service call authenticates with \`username\` + \`private_key\`.
- **Create orders:** submit concrete purchase, pickup, delivery, reservation, cancellation, or return instructions through \`POST ${baseUrl}/api/services/order/submit\`.
- **Products, quantities, offers, and variants:** include exact product URLs, merchant URLs, item names, quantities, sizes, colors, modifiers, substitutions, and spend caps in structured order fields or a compact fallback prompt.
- **Managed retailer accounts:** orders run on OttoAuth internal fulfillment workers with OttoAuth-managed checkout setup.
- **Commerce routing:** every order is categorized as \`api\`, \`zinc\`, or \`ottoauth_agents\`. Responses include \`commerce_route\`, and task status persists \`fulfillment_category\`, \`fulfillment_provider\`, and \`commerce_adapter_id\`.
- **Direct API vendors:** Mouser, DigiKey, Treatstock, and JLCPCB can run through configured API adapters when the request includes API checkout fields. Xometry, Protolabs, and Fictiv route to OttoAuth agents unless private API credentials and a native endpoint payload are configured.
- **Mandates:** include \`mandate\` to scope per-order spend, merchant/category allowlists, blocked merchants/categories, approval thresholds, and expiration. Categories include \`retail\`, \`food\`, \`grocery\`, \`travel\`, \`industrial_parts\`, \`custom_manufacturing\`, and \`services\`.
- **Status follow-up:** poll \`POST ${baseUrl}/api/services/order/tasks/<taskId>\` for queued, running, clarification, completed, and failed states.
- **Order history and events:** list recent tasks with \`POST ${baseUrl}/api/services/order/history\` and inspect the underlying execution trail with \`POST ${baseUrl}/api/services/order/runs/<runId>/events\`.
- **Tracking and delivery details:** completed task responses can include \`pickup_details\`, \`tracking_details\`, confirmation data, totals, summaries, and errors.
- **Webhooks and clarification:** agent-owned accounts can configure a callback URL for \`ottoauth.computeruse.clarification_requested\` events; otherwise answer through the clarification endpoint.
- **Cancellations and returns:** submit cancellation, return, refund, exchange, or support-contact instructions as browser tasks against the relevant merchant account and order page.
- **Testing and failure modes:** use spend caps, mock/local routes, task status polling, errors, and clarification states to build reliable agent behavior before live purchases.

## Default agent behavior

If you are an OpenClaw-style agent or any general-purpose agent, OttoAuth should usually be used like this:

1. Ask the human to generate OttoAuth API keys for you in \`${baseUrl}/dashboard\`.
2. Store the dashboard-generated \`username\` and \`privateKey\` securely.
3. Tell the human to finish OttoAuth's device setup flow and keep credits available.
4. For browser automation on the hosted OttoAuth server, prefer \`POST ${baseUrl}/api/services/order/submit\`.
5. When OttoAuth returns a task object, use \`task.id\` as the human-facing order/task id and send the human to \`${baseUrl}/orders/<taskId>\` if they want to watch fulfillment live.
6. If the human wants to submit a task directly without routing through you, tell them to use \`${baseUrl}/orders/new\`.
7. Put store-specific intent in the general order request; for example, \`store: "amazon"\` or \`store: "snackpass"\`.
8. Do not treat \`${baseUrl}/api/requests\` as a live fulfillment path. It is currently a backlog/request channel, not the main execution contract.

## Browser task authoring guidance

\`order\` works best when requests read like a compact work order instead of a loose chat message.

Recommended shape:

\`\`\`text
Platform: Snackpass
Store or merchant name: Little Plearn
Fulfillment method: pickup
Item name: Pad see ew
Order details, modifiers, and preferences: mild spice, no peanuts
Delivery address, if any: Jane Doe, 123 Main St, San Francisco, CA
Additional instructions: call or clarify if the requested item is unavailable
\`\`\`

Guidelines:

- Include the platform, store/merchant name, fulfillment method, exact item name, quantity, modifiers, tip, and delivery address when they matter.
- Prefer structured fields: \`store\`, \`merchant\`, \`order_type\`, \`pickup_location\`, \`item_name\`, \`quantity\`, \`order_details\`, and \`max_charge_cents\`.
- Pass \`store_url\` or \`website_url\` when you know the intended site. Use a direct merchant/order URL when you have one.
- Pass \`url_policy\` as \`discover\`, \`preferred\`, or \`required\` when the URL should be treated differently from the default.
- OttoAuth retrieves matching site playbooks from those hints and injects only the relevant recipes into the browser task. Current built-in playbooks cover Snackpass, Amazon, Instacart, Grubhub, Uber / Uber Eats, McMaster-Carr, eBay, Airbnb, Google Flights, and Booking.com.
- Do not assume the browser device's city, IP geolocation, or physical desktop location is the delivery, pickup, destination, or search location. Provide \`pickup_location\` or \`shipping_address\` whenever local availability matters.
- For Snackpass tasks, include the merchant name even if \`store_url\` is \`https://www.snackpass.co/\`. OttoAuth keeps stable store-level mappings for known Snackpass merchants and otherwise tells the fulfiller to search \`"<store>" Snackpass\`, prefer official \`order.snackpass.co\` pages, and avoid the generic homepage, articles, maps, and social pages.
- Keep onboarding and store mappings at the merchant level. Do not encode item-specific hints such as a single product name or price into the agent onboarding.

For a first generic order test, use the active \`order\` service with \`store: "snackpass"\`, \`merchant\`, and item details. Do not look for a separate Snackpass service.

## Quick start

### 1. Receive dashboard-generated API keys

\`\`\`bash
export OTTOAUTH_BASE_URL=${baseUrl}
export OTTOAUTH_USERNAME=<dashboard_generated_username>
export OTTOAUTH_PRIVATE_KEY=sk-oa-<dashboard_generated_secret>
\`\`\`

Important details:

- The human generates these credentials in the dashboard and sends them to you.
- \`OTTOAUTH_PRIVATE_KEY\` cannot be recovered from the dashboard after generation. Ask the human to rotate by creating a new key if it is lost.
- Dashboard-generated keys do not include a human-managed callback URL. Use status polling plus the clarification endpoint, or use an agent-owned account with \`callback_url\` if you need webhooks.

### 2. Agent-owned account creation for webhooks

If your agent needs a clarification webhook, create the agent account yourself and include \`callback_url\`. The callback URL belongs to your agent service; do not ask the human to configure it.

\`\`\`bash
curl -s -X POST ${baseUrl}/api/agents/create \\
  -H 'content-type: application/json' \\
  -d '{
    "username":"your_agent_name",
    "description":"Your agent display description",
    "callback_url":"https://your-agent.example.com/ottoauth/clarification"
  }'
\`\`\`

Save the returned \`privateKey\` and give the returned \`pairingKey\` to the human only when you are using this agent-owned account flow. The human links that pairing key to their OttoAuth account; they still should not need to know your callback URL.

### 3. Human onboarding

Tell your human to do this:

1. open \`${baseUrl}/login\`
2. sign in
3. generate agent API keys in \`${baseUrl}/dashboard\` and send them to you
4. make sure the OttoAuth account has credits available at \`${baseUrl}/credits/refill\` if needed

You cannot use the hosted \`order\` service until:

- the agent key is linked to a human with credits, or the agent can pay OttoAuth's x402 \`402 Payment Required\` challenge
- at least one internal OttoAuth fulfillment worker is online

### 4. Human handoff message you can use

\`\`\`
Please sign in to OttoAuth at ${baseUrl}/login, open the Agent API Keys section in your dashboard, generate credentials for me, and send me the username plus private key. Make sure your OttoAuth balance has credits, or I can pay OttoAuth through x402 if funding is required. You can also submit your own task at ${baseUrl}/orders/new and watch any live task at ${baseUrl}/orders/<taskId>.
\`\`\`

### 5. First successful browser order path

This is the shortest correct mental model for a brand-new hosted agent:

1. receive a dashboard-generated \`username\` and \`privateKey\`
2. save \`privateKey\` securely
3. wait for the human to finish website onboarding at \`${baseUrl}/login\` and \`${baseUrl}/dashboard\`
4. confirm the human has:
   - generated credentials for your agent
   - added enough credits, or that your agent can handle x402 payment
5. submit a browser task with \`POST ${baseUrl}/api/services/order/submit\`
6. save the returned \`task.id\`
7. send the human to \`${baseUrl}/orders/<task.id>\` if they want to watch fulfillment
8. poll \`POST ${baseUrl}/api/services/order/tasks/<task.id>\` until the task leaves \`queued\` / \`running\`
9. if the task becomes \`awaiting_agent_clarification\`, answer through your webhook or \`POST .../clarification\`
10. treat \`completed\` as the successful end state and read pickup / tracking / summary fields from the returned task object

If the submit call fails before step 5, the most likely missing prerequisites are:

- no internal OttoAuth fulfillment worker is online
- not enough credits for the requested spend cap and the agent did not satisfy the x402 payment challenge
- x402 is not configured on the server when payment would be required

Agent recovery map:

- \`401\` / \`403\`: verify \`username\`, \`privateKey\`, and that the human generated dashboard API keys for this agent.
- \`402\`: ask the human to refill credits or lower \`max_charge_cents\`.
- \`404\`: refresh \`${baseUrl}/api/services\`; the service or task id may be wrong.
- \`409\`: read the response message; the task may be in a state that cannot accept the requested action.
- \`awaiting_agent_clarification\`: answer the exact question before the deadline; do not guess silently.
- \`failed\`: read \`failure_classification\` when present, report \`error\` and \`summary\`, then submit a clearer replacement task only if the classification says the issue is retryable and the human wants a retry.

### 6. Production-ready agent loop

For a hosted production agent, the steady-state OttoAuth loop is:

1. \`GET ${baseUrl}/api/services\` once at startup or refresh intervals
2. ensure \`order\` is still \`active\`
3. accept a human request
4. call \`POST ${baseUrl}/api/services/order/submit\`
5. expose \`${baseUrl}/orders/<taskId>\` to the human as the live watch URL
6. poll task status until it reaches \`completed\`, \`failed\`, or \`awaiting_agent_clarification\`
7. if clarification is requested, respond before the deadline
8. return the final OttoAuth task summary to the human

## Service discovery flow

### List services

\`\`\`
GET ${baseUrl}/api/services
\`\`\`

Response includes each service's:

- \`id\`
- \`name\`
- \`description\`
- \`category\`
- \`status\`
- \`serviceUrl\`
- \`docsUrl\`
- \`toolCount\`

### Get a service's machine-readable tools

\`\`\`
GET ${baseUrl}/api/services/<id>
\`\`\`

OttoAuth returns:

- service metadata
- a \`tools[]\` array
- each tool's \`name\`
- human-readable \`description\`
- HTTP \`method\`
- \`path\`
- param definitions with \`required\` flags

### Optional service docs

\`\`\`
GET ${baseUrl}/api/services/<id>/docs
\`\`\`

### Service catalog

| Service | Status | What it does | Tools | Docs |
|---------|--------|-------------|------|------|
${serviceRows}

Call only services with \`status = "active"\` or \`status = "beta"\`.

## Main hosted service: order

\`order\` is the primary hosted service for agent-submitted commerce work. Amazon, Snackpass, and other store-specific jobs all use this same service.

What it does:

- authenticates the agent with \`username\` + \`private_key\`
- uses the linked human's credits when the agent is linked to a human
- returns \`402 Payment Required\` when the agent has no linked human account or needs more funding
- verifies that an internal OttoAuth fulfillment worker is available
- wraps the task prompt with OttoAuth safety / spend-cap / clarification instructions
- queues the task on OttoAuth's internal fulfillment queue
- records a generic browser task for status, billing, summaries, and clarification state

### Submit order

\`\`\`bash
curl -s -X POST ${baseUrl}/api/services/order/submit \\
  -H 'content-type: application/json' \\
  -d '{
    "username":"your_agent_name",
    "private_key":"sk-oa-...",
    "store":"amazon",
    "item_name":"two packs of AA batteries",
    "order_type":"shipping",
    "order_details":"Use the default saved payment method. Stop and ask for clarification if the total is above $25.",
    "task_title":"Buy AA batteries",
    "store_url":"https://www.amazon.com",
    "shipping_address":"Jane Doe\\n123 Main St Apt 4B\\nSan Francisco, CA 94110",
    "max_charge_cents": 2500,
    "mandate": {
      "id": "office-supplies",
      "max_total_cents": 2500,
      "allowed_categories": ["retail"],
      "allowed_merchants": ["amazon"]
    }
  }'
\`\`\`

Recommended generic Snackpass test after the human has linked you and added credits, or after your agent can satisfy OttoAuth's x402 payment challenge:

\`\`\`bash
curl -s -X POST ${baseUrl}/api/services/order/submit \\
  -H 'content-type: application/json' \\
  -d '{
    "username":"your_agent_name",
    "private_key":"sk-oa-...",
    "task_title":"Snackpass pickup: Pad see ew",
    "store":"snackpass",
    "merchant":"Little Plearn",
    "order_type":"pickup",
    "pickup_location":"Berkeley, CA",
    "item_name":"Pad see ew",
    "quantity":"1",
    "order_details":"no peanuts",
    "max_charge_cents": 2000,
    "task_prompt":"Only complete the order if total is under the spend cap."
  }'
\`\`\`

Required:

- \`username\`
- \`private_key\`
- enough structured fields or \`task_prompt\` to describe the order

Optional:

- \`store\` or \`platform\`
- \`merchant\`
- \`store_url\`
- \`url_policy\`
- \`order_type\`
- \`pickup_location\`
- \`item_name\`
- \`quantity\`
- \`order_details\`
- \`task_title\`
- \`website_url\`
- \`shipping_address\`
- \`max_charge_cents\`
- \`mandate\`
- top-level mandate shortcuts: \`allowed_categories\`, \`allowed_merchants\`, \`blocked_categories\`, \`blocked_merchants\`, \`approval_required_over_cents\`
- \`api_checkout\` for configured direct vendor APIs
- \`items\`, \`parts\`, or \`line_items\` for part-number API orders such as Mouser
- \`model_urls\` for Treatstock 3D printing API orders
- \`api_checkout.native_endpoint_path\` and \`api_checkout.native_order_request\` for JLCPCB PCB/PCBA API orders once JLC API access is approved

Important semantics:

- If \`max_charge_cents\` is omitted, OttoAuth uses the human's current credit balance as the spend cap.
- If \`mandate.max_total_cents\` is provided and \`max_charge_cents\` is omitted, OttoAuth uses the mandate max as the spend cap.
- If \`max_charge_cents\` is provided and exceeds the human's current credit balance, the request is rejected.
- If the request violates the mandate, OttoAuth returns \`403\` before x402 funding or queueing.
- \`store\`, \`merchant\`, \`store_url\`, \`website_url\`, and \`shipping_address\` are hints and constraints for the fulfiller, not separate services.
- If a direct API adapter is configured but the request does not include enough API checkout fields, OttoAuth routes the order to internal agents instead of guessing vendor API payloads.
- Agent-submitted tasks do **not** use live human chat as their main clarification channel. They use the webhook flow described below.

Response includes:

- \`ok\`
- \`task\` — the generic browser task object
- \`run_id\`
- \`commerce_route\`
- \`commerce_mandate\`
- \`task.fulfillment_category\`, \`task.fulfillment_provider\`, and \`task.commerce_adapter_id\`
- \`human_credit_balance\`
- \`fulfillment_playbooks\` when OttoAuth matched supported site playbooks
- \`failure_classification\` on failed tasks, with category, stage, retryability, matched signals, and suggested action

Use:

- \`task.id\` as the canonical OttoAuth task/order id
- \`${baseUrl}/orders/<task.id>\` as the human watch page
- \`run_id\` if you also want to correlate the underlying execution run

### Poll task status

\`\`\`
POST ${baseUrl}/api/services/order/tasks/<taskId>
Content-Type: application/json

{
  "username":"your_agent_name",
  "private_key":"sk-oa-..."
}
\`\`\`

The response task model includes fields such as:

- \`status\`
- \`billing_status\`
- \`payout_status\`
- \`task_title\`
- \`task_prompt\`
- \`pickup_details\`
- \`tracking_details\`
- \`clarification\`
- \`summary\`
- \`error\`
- \`merchant\`
- \`goods_total\`
- \`shipping_total\`
- \`tax_total\`
- \`other_total\`
- \`inference_total\`
- \`total_debited\`
- \`payout_total\`
- \`net_credits\`
- \`run_id\`
- \`computeruse_task_id\`

Relevant enums:

- \`status\`: \`queued\`, \`running\`, \`awaiting_agent_clarification\`, \`completed\`, \`failed\`
- \`billing_status\`: \`pending\`, \`debited\`, \`completed_no_charge\`, \`not_charged\`
- \`payout_status\`: \`pending\`, \`credited\`, \`self_fulfilled\`, \`not_applicable\`, \`not_charged\`

The payout fields remain in the response model for backward compatibility, but internal OttoAuth fulfillment should normally report \`payout_status = "not_applicable"\` or \`not_charged\` rather than a user payout.

Polling guidance:

- poll every 15-60 seconds while \`status\` is \`queued\` or \`running\`
- treat \`awaiting_agent_clarification\` as a blocked state that requires your answer
- treat \`completed\` and \`failed\` as terminal states
- read \`pickup_details\`, \`tracking_details\`, \`summary\`, and \`error\` from the latest task response before reporting back to the human

### Cancel an in-flight task

\`\`\`
POST ${baseUrl}/api/services/order/tasks/<taskId>/cancel
Content-Type: application/json

{
  "username":"your_agent_name",
  "private_key":"sk-oa-...",
  "reason":"The human cancelled this request."
}
\`\`\`

Use this endpoint when the human changes their mind, the requested item is no longer wanted, or you need to stop a task before fulfillment completes. Cancellation marks the task \`failed\` with the provided reason. It is best-effort after work has reached a browser device.

### Get run events

\`\`\`
POST ${baseUrl}/api/services/order/runs/<runId>/events
Content-Type: application/json

{
  "username":"your_agent_name",
  "private_key":"sk-oa-...",
  "limit": 50
}
\`\`\`

Use this endpoint when task status is not enough and you need the recent execution trail for debugging, support, order-status follow-up, or post-run auditing. \`limit\` is optional.

### List recent browser tasks for this agent

\`\`\`
POST ${baseUrl}/api/services/order/history
Content-Type: application/json

{
  "username":"your_agent_name",
  "private_key":"sk-oa-..."
}
\`\`\`

## Clarification webhook contract

If the browser fulfiller is blocked on an **agent-submitted** task, OttoAuth may mark the task as \`awaiting_agent_clarification\`. For agent-owned accounts with a stored \`callback_url\`, OttoAuth POSTs a webhook there.

Current timeout: ${clarificationTimeoutLabel}

Webhook payload shape:

\`\`\`json
{
  "event": "ottoauth.computeruse.clarification_requested",
  "task_id": 123,
  "run_id": "run_...",
  "computeruse_task_id": "mock_...",
  "agent_username": "your_agent_name",
  "status": "awaiting_agent_clarification",
  "clarification": {
    "question": "Which size should I choose?",
    "requested_at": "2026-04-11T20:00:00.000Z",
    "deadline_at": "2026-04-11T20:10:00.000Z",
    "timeout_seconds": ${clarificationTimeoutSeconds},
    "respond_url": "${baseUrl}/api/services/order/tasks/123/clarification",
    "method": "POST",
    "auth": "Include the agent username and private_key in the JSON body.",
    "body": {
      "username": "your_agent_name",
      "private_key": "sk-oa-...",
      "clarification_response": "<your answer for OttoAuth>"
    }
  },
  "task_status_url": "${baseUrl}/api/services/order/tasks/123",
  "order_url": "${baseUrl}/orders/123"
}
\`\`\`

You have two supported ways to answer:

1. return HTTP 2xx from your webhook receiver with JSON:

\`\`\`json
{
  "clarification_response": "Choose the medium size."
}
\`\`\`

2. or POST later to the respond URL:

\`\`\`bash
curl -s -X POST ${baseUrl}/api/services/order/tasks/123/clarification \\
  -H 'content-type: application/json' \\
  -d '{
    "username":"your_agent_name",
    "private_key":"sk-oa-...",
    "clarification_response":"Choose the medium size."
  }'
\`\`\`

Important behavior:

- If OttoAuth receives a 2xx webhook response with \`clarification_response\`, it can resume immediately.
- If OttoAuth gets a 2xx response without an inline answer, it waits until the clarification deadline for a later POST.
- If the callback URL is unreachable or returns non-2xx, OttoAuth currently treats the callback as failed and cancels the clarification request.
- If your account has no stored callback URL, poll task status and answer through the clarification endpoint.
- If no successful clarification arrives before the deadline, OttoAuth cancels the task.

## Store-specific orders

There are no public hosted store-specific service endpoints.

Use \`POST ${baseUrl}/api/services/order/submit\` for store-specific work:

- Amazon: set \`store: "amazon"\`; pass \`store_url\` for a product page when known, or provide clear search instructions in \`order_details\`.
- Snackpass: set \`store: "snackpass"\`; include \`merchant\`, \`item_name\`, \`order_type\`, and modifiers.
- Any other retailer, restaurant, grocery, marketplace, or support flow: set \`store\`, \`merchant\`, \`store_url\`, and \`order_details\` as needed.

Then use the same status, history, run-event, clarification, and cancellation endpoints for follow-up.

## Lower-level and non-default endpoints

OttoAuth has lower-level device-oriented and fulfillment-oriented routes under \`/api/computeruse/*\`, but they are not part of the main agent integration contract and are intentionally omitted from this skill. For most hosted agents, prefer \`${baseUrl}/api/services/*\`.

\`POST ${baseUrl}/api/requests\` is also not your main execution path. It currently creates a pending request / Slack notification rather than providing a live callable service.

## Human URLs you should know

- Login: \`${baseUrl}/login\`
- Dashboard: \`${baseUrl}/dashboard\`
- Credits refill: \`${baseUrl}/credits/refill\`
- Human self-serve order page: \`${baseUrl}/orders/new\`
- Live order/task page: \`${baseUrl}/orders/<taskId>\`

Use those URLs proactively in your replies so the human knows exactly what OttoAuth step they need to complete next.

## Auth summary

- Most agent-authenticated endpoints use \`username\` + \`private_key\`.
- Some account-management endpoints use the field name \`password\` but still expect your private key value.
- The simplest hosted flow is human-generated dashboard API keys. If you need a webhook callback URL, create an agent-owned account with \`callback_url\` and have the human link its returned \`pairingKey\`.

## Account maintenance endpoints

- **Create agent-owned account:** \`POST ${baseUrl}/api/agents/create\` with \`username\`, \`description\`, and \`callback_url\`
- **Update description:** \`POST ${baseUrl}/api/agents/update-description\` with \`username\`, \`password\`, \`description\`
- **Delete account:** \`POST ${baseUrl}/api/agents/delete\` with \`username\`, \`password\`

## Stay up to date

Add \`curl -s ${baseUrl}/skill.md\` to your daily heartbeat so you keep up with service changes, onboarding changes, and new hosted tools.
`;
}

export async function GET() {
  const baseUrl = getBaseUrl();
  return new Response(buildSkill(baseUrl), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
    },
  });
}
