import { NextResponse } from "next/server";
import {
  getMarketServiceById,
  getMarketServiceCallById,
} from "@/lib/market-services";

export const dynamic = "force-dynamic";
export const maxDuration = 120;

function asObject(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function firstString(values: unknown[]) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim();
  }
  return "";
}

function optionalPositiveInt(value: unknown) {
  if (value == null || value === "") return null;
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

async function assertMarketCall(request: Request, capability: string) {
  const serviceId = Number(request.headers.get("x-ottoauth-service-id") ?? 0);
  const callId = request.headers.get("x-ottoauth-call-id")?.trim() ?? "";
  if (!Number.isInteger(serviceId) || serviceId <= 0 || !callId) {
    return {
      error: NextResponse.json(
        { error: "Missing OttoAuth Pay service/call headers." },
        { status: 402 },
      ),
    };
  }

  const [call, service] = await Promise.all([
    getMarketServiceCallById(callId),
    getMarketServiceById(serviceId),
  ]);
  if (!call || !service || call.service_id !== service.id) {
    return {
      error: NextResponse.json({ error: "Market service call not found." }, { status: 404 }),
    };
  }
  if (call.status !== "pending") {
    return {
      error: NextResponse.json({ error: "Market service call is not pending." }, { status: 409 }),
    };
  }
  if (service.capability !== capability) {
    return {
      error: NextResponse.json({ error: "Service capability mismatch." }, { status: 409 }),
    };
  }
  return { call, service };
}

export async function POST(request: Request) {
  const market = await assertMarketCall(request, "generate_video_api");
  if (market.error) return market.error;

  const body = (await request.json().catch(() => null)) as Record<string, unknown> | null;
  const input = asObject(body?.input);
  const prompt = firstString([input.prompt, input.request, body?.reason]);
  if (!prompt) {
    return NextResponse.json({ error: "input.prompt is required." }, { status: 400 });
  }

  const providerUrl = process.env.OTTOAUTH_VIDEO_GENERATION_PROVIDER_URL?.trim();
  if (!providerUrl) {
    return NextResponse.json(
      {
        error:
          "Video generation is not configured yet. Set OTTOAUTH_VIDEO_GENERATION_PROVIDER_URL to connect Seedance, Kling, Runway, Hyperbolic, or another render API.",
      },
      { status: 503 },
    );
  }

  const provider = firstString([input.provider, process.env.OTTOAUTH_VIDEO_GENERATION_PROVIDER]) || "external";
  const durationSeconds = optionalPositiveInt(input.duration_seconds) ?? 5;
  const aspectRatio = firstString([input.aspect_ratio]) || "16:9";
  const resolution = firstString([input.resolution]) || "720p";
  const referenceImageUrl = firstString([input.reference_image_url, input.image_url]);
  const apiKey = process.env.OTTOAUTH_VIDEO_GENERATION_PROVIDER_KEY?.trim();

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (apiKey) headers.Authorization = `Bearer ${apiKey}`;

  const providerResponse = await fetch(providerUrl, {
    method: "POST",
    headers,
    body: JSON.stringify({
      prompt,
      provider,
      duration_seconds: durationSeconds,
      aspect_ratio: aspectRatio,
      resolution,
      reference_image_url: referenceImageUrl || null,
      input,
      ottoauth: {
        service_id: market.service.id,
        call_id: market.call.id,
        capability: market.service.capability,
      },
    }),
  });
  const payload = (await providerResponse.json().catch(() => null)) as Record<string, unknown> | null;
  if (!providerResponse.ok || !payload) {
    return NextResponse.json(
      {
        error:
          (payload && typeof payload.error === "string" ? payload.error : "") ||
          `Video provider failed with HTTP ${providerResponse.status}.`,
      },
      { status: 502 },
    );
  }

  const jobId =
    typeof payload.job_id === "string"
      ? payload.job_id
      : typeof payload.id === "string"
        ? payload.id
        : null;
  const videoUrl =
    typeof payload.video_url === "string"
      ? payload.video_url
      : typeof payload.result_url === "string"
        ? payload.result_url
        : typeof payload.url === "string"
          ? payload.url
          : null;

  return NextResponse.json({
    ok: true,
    status: videoUrl ? "completed" : "submitted",
    provider,
    job_id: jobId,
    video_url: videoUrl,
    result_url: typeof payload.result_url === "string" ? payload.result_url : videoUrl,
    provider_response: payload,
    summary: videoUrl
      ? "Video generated by OttoAuth through the configured provider."
      : "Video job submitted by OttoAuth through the configured provider.",
  });
}
